language: go
go:
  - 1.14.x
env: GO111MODULE=on

git:
  depth: 1
  submodules: false

install:
  - make

before_script:
script:
  - make alltest

after_success:
  - bash <(curl -s https://codecov.io/bash)